# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
# fluent-bit
specSchema: "Application"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: fluent-bit
version: 0.48.9
description: "Fluent Bit"
kind: extension

helmRegistry: "fluent-bit"
chartName: "fluent-bit"
chartVersion: "0.48.9"

profiles:
  - name: default
    displayName: "default"
    valuesFileName: "values-fluent-bit.yaml"
    deploymentRequirements:
    - name: cert-manager
      version: 0.1.0
      deploymentProfileName: default-profile
