# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
# rancher local-path-provisioner
specSchema: "Application"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: rancher-lpp
version: 0.0.31-dev

description: "Rancher Local Path Provisioner"
kind: extension

helmRegistry: "intel-rs-helm"
chartName: "edge-orch/en/charts/local-path-provisioner"
chartVersion: "0.0.1-dev"

profiles:
  - name: default
    displayName: "default"
    valuesFileName: "values-rancher-lpp.yaml"
