# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
# rancher local-path-provisioner
specSchema: "Application"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: rancher-lpp
version: 0.0.32-dev

description: "Rancher Local Path Provisioner"
kind: extension

helmRegistry: "registry-oci.kind.internal"
chartName: "catalog-apps-sample-org-sample-project/local-path-provisioner"
chartVersion: "0.0.2-dev"

profiles:
  - name: default
    displayName: "default"
    valuesFileName: "values-rancher-lpp.yaml"
