# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: openebs
  name: openebs-deny-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
    - from:
        - podSelector: {}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: openebs
  name: openebs-allow-metrics-port-from-observability
spec:
  podSelector:
    matchLabels:
  ingress:
    - ports:
        - port: 9100
        - port: 9101
        - port: 9500
      from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
