# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubevirt-helper.fullname" . }}
  labels:
    {{- include "kubevirt-helper.labels" . | nindent 4 }}
data:
  logging.yaml: |-
{{ toYaml .Values.logging | indent 4 }}