# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubevirt-helper.fullname" . }}-rbac
  labels:
    {{- include "kubevirt-helper.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - kubevirt.io
    resources:
      - virtualmachineinstances
    verbs:
      - get
      - list
      - delete
      - update
  - apiGroups:
      - kubevirt.io
    resources:
      - virtualmachines
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - subresources.kubevirt.io
    resources:
      - virtualmachines/restart
    verbs:
      - "*"
  - apiGroups:
      - cdi.kubevirt.io
    resources:
      - datavolumes
    verbs:
      - delete

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubevirt-helper.fullname" . }}-rbac
  labels:
    {{- include "kubevirt-helper.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubevirt-helper.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kubevirt-helper.fullname" . }}-rbac
  apiGroup: rbac.authorization.k8s.io
