# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubevirt-helper.serviceAccountName" . }}
  labels:
    {{- include "kubevirt-helper.labels" . | nindent 4 }}
{{- end }}
