# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubevirt-helper.fullname" . }}
  labels:
    {{- include "kubevirt-helper.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.ports.webhook.port }}
      targetPort: {{ .Values.config.kubevirtHelper.webhookServer.port }}
      protocol: {{ .Values.service.ports.webhook.protocol }}
      name: webhook
  selector:
    {{- include "kubevirt-helper.selectorLabels" . | nindent 4 }}