# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-debug
spec:
  containers:
  - name: gpu-debug
    image: {{ .Values.registry }}/{{ .Values.image }}
    imagePullPolicy: Always
    command: ["/bin/bash",  "-c", "ls /dev/dri/; xpu-smi discovery; lshw -C display; python3 /usr/share/openvino/samples/python/hello_query_device/hello_query_device.py;  sleep 3600"]
    resources:
          limits:
            gpu.intel.com/i915: 1
    securityContext:
          privileged: true
          #runAsGroup: 110