# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skupper-hello-world-backend.fullname" . }}
  labels:
    {{ include "skupper-hello-world-backend.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{ include "skupper-hello-world-backend.selectorLabels" . | nindent 4 }}
