# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
# observability-config
specSchema: "Application"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: observability-config
version: 0.0.2
description: "Observability Config"
kind: extension

helmRegistry: "intel-rs-helm"
chartName: "edge-orch/en/charts/observability-config"
chartVersion: "0.0.2"

profiles:
  - name: default
    displayName: "default"
    valuesFileName: "values-observability-config.yaml"
