# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
{{- if not .Values.cert_manager -}}
{{- if .Values.operator.admissionControllers.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: operator-webhook-service
  namespace: {{ .Release.Namespace }}
data: {{ include "sriov_operator_cert" . | nindent 2 }}
{{- end }}
---
{{- if .Values.operator.admissionControllers.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: network-resources-injector-secret
  namespace: {{ .Release.Namespace }}
data: {{ include "sriov_resource_injector_cert" . | nindent 2 }}
{{- end }}
{{- end }}

