# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
# Coredns service template definition
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-coredns
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: coredns
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ .Values.staticIp }}
spec:
  allocateLoadBalancerNodePorts: false
  ports:
  - name: coredns
    port: 53
    protocol: UDP
    targetPort: dns-port
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: edgedns-metrics
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: coredns
  type: LoadBalancer
