# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
{{- if .Values.edgednsServiceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: edgedns-metrics
  namespace: "{{ .Values.observabilityNamespace }}"
  labels:
    app.kubernetes.io/component: edgedns
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: edgedns
      app.kubernetes.io/component: coredns
  endpoints:
  - port: metrics
    scheme: http
    relabelings:
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - sourceLabels: [__meta_kubernetes_service_name]
        regex: ".*-coredns"
        action: keep
      - sourceLabels: [__address__]
        regex: ".*:9153"
        action: keep
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        action: replace
        targetLabel: instance
      - sourceLabels: [__meta_kubernetes_pod_name]
        action: replace
        targetLabel: kubernetes_pod_name
  namespaceSelector:
    matchNames:
      - "{{ .Release.Namespace }}"
{{- end }}
