# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-etcd-dns
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: etcd-dns
spec:
  serviceName: {{ .Release.Name }}-etcd-dns
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: etcd-dns
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: etcd-dns
    spec:
      securityContext:
        fsGroup: 10001
      initContainers:
        - name: init-etcd-config
          image: busybox:1.35.0
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            runAsUser: 10001
            runAsGroup: 10001
          command:
            - /bin/sh
            - -c
            - |
              IP=$(hostname -i)
              PEERS=""
              for i in $(seq 0 $((${CLUSTER_SIZE} - 1))); do
                PEERS="${PEERS}${PEERS:+,}${SET_NAME}-${i}=https://${SET_NAME}-${i}.${SET_NAME}:2380"
              done
              tee /home/etcd/etcd_config.yml << END
              name: ${HOSTNAME}
              listen-peer-urls: https://${IP}:2380
              listen-client-urls: https://${IP}:2379,http://127.0.0.1:2379
              advertise-client-urls: https://${HOSTNAME}.${SET_NAME}:2379
              initial-advertise-peer-urls: https://${HOSTNAME}.${SET_NAME}:2380
              initial-cluster-token: etcd-cluster-1
              initial-cluster: ${PEERS}
              initial-cluster-state: new
              data-dir: /var/run/etcd/default.etcd
              client-transport-security:
                client-cert-auth: true
                cert-file: /certs/tls.crt
                key-file: /certs/tls.key
                trusted-ca-file: /certs/ca.crt
              peer-transport-security:
                client-cert-auth: true
                trusted-ca-file: /certs/ca.crt
                cert-file: /certs/tls.crt
                key-file: /certs/tls.key
              auto-compaction-mode: periodic
              END
          env:
            - name: CLUSTER_SIZE
              value: "{{ .Values.replicaCount }}"
            - name: SET_NAME
              value: {{ .Release.Name }}-etcd-dns
          volumeMounts:
            - name: etcd-config
              mountPath: /home/etcd
      containers:
        - name: {{ .Release.Name }}-etcd-dns
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            runAsUser: 10001
            runAsGroup: 10001
          image: quay.io/coreos/etcd:v3.5.15
          env:
            - name: ETCD_CONFIG_FILE
              value: /home/etcd/etcd_config.yml
          volumeMounts:
            - name: datadir
              mountPath: /var/run/etcd
            - name: edgedns-etcd-client-tls
              mountPath: /certs
            - name: etcd-config
              mountPath: /home/etcd
          command: ["/usr/local/bin/etcd"]
          ports:
            - containerPort: 2379
              name: client
              protocol: TCP
            - containerPort: 2380
              name: peer
              protocol: TCP
      volumes:
        - name: datadir
          emptyDir: { }
        - name: etcd-config
          emptyDir: { }
        - name: edgedns-etcd-client-tls
          secret:
            secretName: edgedns-etcd-client-tls
