# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lp-{{ .Release.Name }}-etcd-tls-cert
spec:
  # Secret names are always required
  commonName: edgedns-etcd-dns
  secretName: edgedns-etcd-client-tls
  duration: 720h # 30d
  renewBefore: 168h # 7d
  subject:
    organizations:
      - Intel Corporation
    countries:
      - US
    organizationalUnits:
      - Edge Orchestrator
  usages:
    - digital signature
    - client auth
    - server auth
  dnsNames:
    - {{ .Release.Name }}-etcd-dns
    - etcd.edgedns.node.intel.corp
    - etcd.edgedns
    {{- range $idx := until (int .Values.replicaCount) }}
    - {{ $.Release.Name }}-etcd-dns-{{ $idx }}.{{ $.Release.Name }}-etcd-dns
    {{- end }}
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  issuerRef:
    name: edgedns-{{ .Release.Name }}-issuer
    kind: Issuer
