# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-external-dns
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: external-dns
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: external-dns
    spec:
      serviceAccountName: {{ .Release.Name }}-external-dns
      containers:
      - name: {{ .Release.Name }}-external-dns
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsUser: 65532
        image: registry.k8s.io/external-dns/external-dns:v0.14.2
        volumeMounts:
          - name: edgedns-external-dns-client-tls
            mountPath: /certs
        args:
        - --source=service
        - --source=ingress
        - --provider=coredns
        - --registry=txt
        - --log-level=info
        - --interval=15s
        - --publish-internal-services
        env:
          - name: ETCD_URLS
            value: https://{{ .Release.Name }}-etcd-dns:2379
          - name: ETCD_CA_FILE
            value: /certs/ca.crt
          - name: ETCD_CERT_FILE
            value: /certs/tls.crt
          - name: ETCD_KEY_FILE
            value: /certs/tls.key
          - name: ETCD_TLS_SERVER_NAME
            value: {{ .Release.Name }}-etcd-dns
      volumes:
        - name: edgedns-external-dns-client-tls
          secret:
            secretName: edgedns-external-dns-client-tls
