# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
# Issuer for edgedns namespace
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: edgedns-{{ .Release.Name }}-issuer
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "3"
spec:
  ca:
    secretName: root-secret
