# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-{{ .Release.Name }}-etcd-dns-client
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: etcd-dns
  ingress:
  - from:
    - podSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
            app.kubernetes.io/component: external-dns
    - podSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
            app.kubernetes.io/component: coredns
    ports:
    - protocol: TCP
      port: 2379
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-{{ .Release.Name }}-etcd-dns-peer
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: etcd-dns
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/component: etcd-dns
      ports:
        - protocol: TCP
          port: 2380
  policyTypes:
    - Ingress
---
## Network policy to allow metrics collection from edgedns
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: metrics-{{ .Release.Name }}-prometheus
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: coredns
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: observability
      podSelector:
          matchLabels:
            app.kubernetes.io/instance: prometheus-prometheus
            app.kubernetes.io/name: prometheus
    ports:
    - protocol: TCP
      port: 9153
  policyTypes:
  - Ingress
---
## Network policy to allow external access to Edgedns on UDP port 53
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-external-access
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: coredns
  ingress:
    - ports:
       - protocol: UDP
         port: 53
  policyTypes:
  - Ingress
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: allow-inside-namespace-egress
  namespace: edge-system
spec:
  selector: all()
  types:
    - Egress
  egress:
    - action: Allow
      destination:
        namespaceSelector: kubernetes.io/metadata.name == 'edge-system'
        selector: app.kubernetes.io/instance == 'edgedns'

