# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
policies:
  exemptImages: ["quay.io/kubevirt/virt-launcher:v1.1.1, quay.io/kubevirt/cdi-importer:v1.58.0"]
  constraints:
    capabilities:
      enabled: true
      excludedNamespaces:
        - metallb-system
        - observability
      allowedCapabilities: ["NET_BIND_SERVICE"]
    hostNetwork:
      enabled: true
      excludedNamespaces:
        - calico-system
        - kube-system
        - kubevirt
        - metallb-system
        - observability
        - openebs
        - sriov-network-operator
        - tigera-operator
    volumeTypes:
      enabled: true
      excludedNamespaces:
        - akri
        - calico-system
        - cattle-system
        - kube-system
        - kubevirt
        - cdi
        - nfd
        - observability
        - openebs
        - sriov-network-operator
        - tigera-operator
        - local-path-storage
    hostNamespace:
      enabled: true
      excludedNamespaces:
        - kubevirt
        - sriov-network-operator
    hostPorts:
      enabled: true
      excludedNamespaces:
        - calico-system
        - kube-system
        - metallb-system
        - observability
      allowedHostPort: false
      allowedHostPortMin: 0
      allowedHostPortMax: 0
    privilegedContainer:
      enabled: true
      excludedNamespaces:
        - calico-system
        - kube-system
        - kubevirt
        - observability
        - openebs
        - sriov-network-operator
    privilegedEscalation:
      enabled: true
      excludedNamespaces:
        - calico-system
        - kube-system
        - openebs
    readOnlyFs:
      enabled: true
      excludedNamespaces:
        - akri
        - calico-system
        - cattle-fleet-system
        - cattle-system
        - cdi
        - cert-manager
        - edge-system
        - kube-system
        - kubevirt
        - observability
        - openebs
        - sriov-network-operator
        - tigera-operator
      # exemptContainerNames only applies to ReadOnlyRootFileSystem
      # constraint to unblock the VM deployment
      exemptContainerNames: ["volumecontainervolume, volumecontainervolume-init"]
    sysctls:
      enabled: true
      excludedNamespaces:
        - calico-system
        - kube-system
      allowedSysctls: [
        "kernel.shm_rmid_forced",
        "net.ipv4.ip_local_port_range",
        "net.ipv4.ip_unprivileged_port_start",
        "net.ipv4.tcp_syncookies",
        "net.ipv4.ping_group_range"
        # - "*" # * may be used to allow all sysctls
      ]
metricsPort: 8888
podMonitor:
  enabled: true
networkPolicies:
  enabled: true
