# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
# Gatekeeper
specSchema: "Application"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: gatekeeper
version: 3.17.1
description: "Gatekeeper"
kind: extension

helmRegistry: "gatekeeper"
chartName: "gatekeeper"
chartVersion: "3.17.1"

profiles:
  - name: default
    displayName: "default"
    valuesFileName: "values-gatekeeper.yaml"
---
# gatekeeper-constraints
specSchema: "Application"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: gatekeeper-constraints
version: 1.1.0
description: "Gatekeeper Constraints"
kind: extension

helmRegistry: "intel-rs-helm"
chartName: "edge-orch/en/charts/gatekeeper-constraints"
chartVersion: "1.1.0"

profiles:
  - name: baseline
    displayName: "baseline"
    valuesFileName: "values-gatekeeper-constraints-baseline.yaml"
  - name: restricted
    displayName: "restricted"
    valuesFileName: "values-gatekeeper-constraints-restricted.yaml"
  - name: privileged
    displayName: "privileged"
    valuesFileName: "values-gatekeeper-constraints-more-privileged.yaml"
