# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: skupper-hello-world-frontend
description: A Helm chart for Skupper Hello World Frontend App

type: application
version: 0.3.0
appVersion: "1.0"
