# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Default values for skupper-hello-world-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
replicaCount: 1

fullnameOverride: "skupper-hello-world-frontend"

image:
  repository: quay.io/skupper/hello-world-frontend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  port: 8080

backend:
  address:
    "http://skupper-hello-world-backend.interconnect.svc.cluster.local:8080"
