# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: capabilities
  annotations:
    metadata.gatekeeper.sh/title: "Capabilities"
    description: >-
        Controls Linux capabilities on containers. Corresponds to the
        `allowedCapabilities` field in the PodSecurityPolicy.
spec:
  crd:
    spec:
      names:
        kind: Capabilities
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          description: >-
            Controls Linux capabilities on containers. Corresponds to the
            `allowedCapabilities` fields in the PodSecurityPolicy.
          properties:
            exemptImages:
              description: >-
                Any container that uses an image that matches an entry in this list will be excluded
                from enforcement. Prefix-matching can be signified with `*`. For example: `my-image-*`.
              type: array
              items:
                type: string
            namespaceOnlyExemptImages:
              description: >-
                Any container running in a specific namespace that uses an image that matches an entry
                in this list will be excluded from enforcement.  Prefix-matching can
                be signified with `*`. For example: `my-image-*`.
              type: array
              items:
                type: string
            allowedCapabilities:
              type: array
              description: "A list of Linux capabilities that can be added to a container."
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
{{.Files.Get "rego/capabilities/capabilities_policy.rego" | indent 8 }}
