# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.policies.constraints.hostNetwork.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: HostNetwork
metadata:
  name: host-network
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "3"
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
    {{- range .Values.policies.constraints.hostNetwork.excludedNamespaces }}
      - {{ . | quote }}
    {{- end }}
    labelSelector:
      matchExpressions:
        - key: bypass-host-network
          operator: DoesNotExist
    namespaceSelector:
      matchExpressions:
        - key: bypass-host-network
          operator: DoesNotExist
  enforcementAction: deny
{{- end }}
