# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.policies.constraints.hostPorts.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: HostPorts
metadata:
  name: host-ports
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "3"
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
    {{- range .Values.policies.constraints.hostPorts.excludedNamespaces }}
      - {{ . | quote }}
    {{- end }}
    labelSelector:
      matchExpressions:
        - key: bypass-host-ports
          operator: DoesNotExist
    namespaceSelector:
      matchExpressions:
        - key: bypass-host-ports
          operator: DoesNotExist
  parameters:
    exemptImages: {{ .Values.policies.exemptImages }}
    allowHostPort: {{ .Values.policies.constraints.hostPorts.allowedHostPort }}
    min: {{ .Values.policies.constraints.hostPorts.allowedHostPortMin }}
    max: {{ .Values.policies.constraints.hostPorts.allowedHostPortMax }}
  enforcementAction: deny
{{- end }}
