# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: hostports
  annotations:
    metadata.gatekeeper.sh/title: "Host Ports"
    description: >-
      Controls usage of host ports by pod containers. If usage of host ports is allowed
      specific port ranges must be specified. Corresponds to the 
      `hostPorts` field in a PodSecurityPolicy.
spec:
  crd:
    spec:
      names:
        kind: HostPorts
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          description: >-
            Controls usage of host ports by pod containers. If usage of host ports is allowed
            specific port ranges must be specified. Corresponds to the 
            `hostPorts` field in a PodSecurityPolicy.
          properties:
            exemptImages:
              description: >-
                Any container that uses an image that matches an entry in this list will be excluded
                from enforcement. Prefix-matching can be signified with `*`. For example: `my-image-*`.
              type: array
              items:
                type: string
            namespaceOnlyExemptImages:
              description: >- 
                Any container running in a specific namespace that uses an image that matches an entry
                in this list will be excluded from enforcement.  Prefix-matching can
                be signified with `*`. For example: `my-image-*`.
              type: array
              items:
                type: string
            allowHostPort:
              description: "Determines if the policy allows the use of hostPort in the pod spec."
              type: boolean
            min:
              description: "The start of the allowed port range, inclusive."
              type: integer
            max:
              description: "The end of the allowed port range, inclusive."
              type: integer
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
{{.Files.Get "rego/hostports/hostports_policy.rego" | indent 8 }}
