# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: allowedsysctls
  annotations:
    metadata.gatekeeper.sh/title: "Allowed Sysctls"
    description: >-
      Controls the `sysctl` profile used by containers.
spec:
  crd:
    spec:
      names:
        kind: AllowedSysctls
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          description: >-
            "Controls the `sysctl` profile used by containers. Corresponds to the `allowedSysctls` fields in a PodSecurityPolicy."
          properties:
            allowedSysctls:
              type: array
              description: "An allow-list of sysctls. `*` allows all sysctls."
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
{{.Files.Get "rego/sysctls/sysctls_policy.rego" | indent 8 }}
