# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.policies.constraints.sysctls.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AllowedSysctls
metadata:
  name: allowed-sysctls
  namespace: gatekeeper-system
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "3"
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
    {{- range .Values.policies.constraints.sysctls.excludedNamespaces }}
      - {{ . | quote }}
    {{- end }}
    labelSelector:
      matchExpressions:
        - key: bypass-allowed-sysctls
          operator: DoesNotExist
    namespaceSelector:
      matchExpressions:
        - key: bypass-allowed-sysctls
          operator: DoesNotExist
  parameters:
    allowedSysctls: {{ .Values.policies.constraints.sysctls.allowedSysctls }}
  enforcementAction: deny
{{- end }}
