# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
# network-policies
specSchema: "Application"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: network-policies
version: 0.2.0
description: "Network Policies"
kind: extension

helmRegistry: "intel-rs-helm"
chartName: "edge-orch/en/charts/network-policies"
chartVersion: "0.2.0"

profiles:
  - name: default
    displayName: "default"
    valuesFileName: "values-network-policies.yaml"
