# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: default-deny
spec:
  order: 10100
  namespaceSelector: >
    has(projectcalico.org/name) &&
    projectcalico.org/name not in
    {"kube-system", "calico-system", "calico-apiserver", "cattle-system",
    "cattle-fleet-system", "cattle-impersonation-system", "tigera-operator" }
  types:
    - Ingress
    - Egress
  egress:
    - action: Allow
      protocol: UDP
      destination:
        selector: 'k8s-app == "kube-dns"'
        ports:
          - 53
    - action: Allow
      protocol: TCP
      destination:
        selector: 'k8s-app == "kube-dns"'
        ports:
          - 53
    - action: Allow
      protocol: TCP
      destination:
        services:
          name: kubernetes
          namespace: default
