# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: calico-system
  name: calico-system-deny-from-other-namespaces-except-tigera-operator
spec:
  policyTypes:
    - Ingress
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: calico-system
        - namespaceSelector:
            matchLabels:
              name: tigera-operator
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: calico-system
  name: calico-system-allow-metrics-port-from-observability
spec:
  podSelector:
    matchLabels:
  ingress:
    - ports:
        - port: 9094
      from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
