# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: helmchart-installers-allow-egress
spec:
  selector: has(helmcharts.helm.cattle.io/chart)
  order: 100
  types:
    - Egress
  egress:
    - action: Allow
      destination:
        notNets: ["{{ .Values.calico_cidr }}"]
    - action: Pass
