# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skupper-hello-world-frontend.fullname" . }}
  labels:
    {{ include "skupper-hello-world-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "skupper-hello-world-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{include "skupper-hello-world-frontend.selectorLabels" . | nindent 8}}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          args:
            - "--backend={{ .Values.backend.address }}"
