# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skupper-hello-world-frontend.fullname" . }}
  labels:
    {{ include "skupper-hello-world-frontend.labels" . | nindent 4 }}
  annotations:
    service-proxy.app.orchestrator.io/ports: 8080
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{ include "skupper-hello-world-frontend.selectorLabels" . | nindent 4 }}
