# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skupper-hello-world-frontend.fullname" . }}
  labels:
    {{ include "skupper-hello-world-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{ include "skupper-hello-world-frontend.selectorLabels" . | nindent 4 }}
