# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: edgedns
description: A Helm chart for Edge Orchestrator EdgeDNS
type: application
version: 1.4.2
appVersion: 1.4.2
annotations:
  revision: fbda91b32f455ad912ad1772860a5ad3f5b8e1c2
  created: "2025-04-24T16:02:48Z"
