# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
replicaCount: 3
global:
  registry:
    name: registry-rs.edgeorchestration.intel.com/
image:
  # uncomment to set the URL on a specific chart (this overrides global.registry if set)
  # registry:
  #   name: ""
  repository: edge-orch/en/edgedns-coredns
  pullPolicy: IfNotPresent
  tag: ""
staticIp: 192.168.160.250
storageclass: openebs-lvmpv
edgednsServiceMonitor:
  enabled: true
observabilityNamespace: observability
coredns:
  # https://github.com/coredns/rrl
  rrl:
    # responses-per-second ALLOWANCE - the number of positive responses allowed per
    # second. Default 0
    # https://kb.isc.org/docs/aa-01148
    responsesPerSecond: 100
service:
  externalIPs: []
###
extensionImages:
  - registry-rs.edgeorchestration.intel.com/edge-orch/en/edgedns-coredns:1.4.2
  - registry.k8s.io/external-dns/external-dns:v0.14.2
  - quay.io/coreos/etcd:v3.5.15
