# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2023 Intel Corporation
{{- if .Values.networkPoliciesEnabled }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: cdi-deny-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
    - from:
        - podSelector: {}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: cdi-allow-metrics-port-from-observability
spec:
  podSelector:
    matchLabels:
  ingress:
  - ports:
      - port: 8080
    from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: observability
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: cdi-allow-calls-from-api-server
spec:
  podSelector:
    matchLabels:
      cdi.kubevirt.io: cdi-apiserver
  ingress:
    - ports:
        - port: 8443
          protocol: TCP
        - port: 443
          protocol: TCP
      from:
        - podSelector:
            matchLabels:
              component: kube-apiserver
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: allow-egress
  namespace: {{ .Release.Namespace }}
spec:
  selector: has(operator.cdi.kubevirt.io) || has(cdi.kubevirt.io) || has(operator.cdi.kubevirt.io)
  egress:
    - action: Allow
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: cdi-deletion-hook-allow-calls-to-api
  namespace: {{ .Release.Namespace }}
spec:
  selector: job-name == 'cdi-pre-deletion'
  egress:
    - action: Allow
      destination:
        services:
          name: kubernetes
          namespace: default
    - action: Allow
      destination:
        services:
          name: cdi-api
          namespace: {{ .Release.Namespace }}
{{- end }}
