# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
hostname: global.fleet.clusterLabels.edge-orchestrator.intel.com/clustername
nodeUUID: global.fleet.edge-orchestrator.intel.com/host-uuid
image:
  tag: 3.2.9
fullnameOverride: fluent-bit
extraVolumeMounts:
  - name: certs
    mountPath: /opt/fluent-bit/certs
  - name: containerlog
    mountPath: /var/log/containers
    readOnly: true
  - name: podlog
    mountPath: /var/log/pods
    readOnly: true
  - name: syslog
    mountPath: /var/log/syslog
    readOnly: true
  - name: authlog
    mountPath: /var/log/auth.log
    readOnly: true
  - name: rancheragentlog
    mountPath: /var/lib/rancher/rke2/agent/logs
    readOnly: true
  - name: logforward
    mountPath: /run/platform-observability-agent/fluent-bit
extraVolumes:
  - name: certs
    secret:
      secretName: fluent-bit-tls
  - name: containerlog
    hostPath:
      path: /var/log/containers
      type: Directory
  - name: podlog
    hostPath:
      path: /var/log/pods
      type: Directory
  - name: syslog
    hostPath:
      path: /var/log/syslog
      type: File
  - name: authlog
    hostPath:
      path: /var/log/auth.log
      type: File
  - name: rancheragentlog
    hostPath:
      path: /var/lib/rancher/rke2/agent/logs
      type: Directory
  - name: logforward
    hostPath:
      path: /run/platform-observability-agent/fluent-bit
      type: Directory

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 502
  supplementalGroups: [4, 500]
resources:
  limits:
    cpu: 200m
    memory: 400Mi
  requests:
    cpu: 100m
    memory: 200Mi
service:
  port: 24224
rbac:
  nodeAccess: true
testFramework:
  enabled: false
config:
  service: |
    [SERVICE]
      Flush     5
      Log_Level info
      HTTP_Server On
      HTTP_Listen 0.0.0.0
      Health_Check On
#
  inputs: |
    [INPUT] ## Input for syslog
      Name           tail
      Tag            EdgeNode_Syslog
      Path           /var/log/syslog
      Parser         syslog-rfc3164
      Read_from_Head true
      Mem_Buf_Limit 25MB
      Skip_Long_Lines On

    [INPUT] ## Input for auth.log
      Name           tail
      Tag            EdgeNode_AuthLog
      Path           /var/log/auth.log
      Parser         syslog-rfc3164
      Read_from_Head true
      Mem_Buf_Limit 25MB
      Skip_Long_Lines On

    [INPUT] ## Input for container logs
      Name           tail
      Tag            Container.*
      multiline.parser docker, cri
      Path           /var/log/containers/*.log
      Read_from_Head true
      Mem_Buf_Limit 25MB
      Skip_Long_Lines On

    [INPUT] ## Input for Rancher agent log (kubelet log)
      Name           tail
      Tag            EdgeNode_KubeletLog
      Path           /var/lib/rancher/rke2/agent/logs/kubelet.log
      Mem_Buf_Limit 25MB
      Read_from_Head true

    [INPUT] ## Input for logs/traces received on port
      Name         opentelemetry
      Tag          EdgeNode_OtelLogs
      Listen       0.0.0.0
      Port         24224
      tls          on
      tls.verify   on
      tls.ca_file   /opt/fluent-bit/certs/ca.crt
      tls.crt_file  /opt/fluent-bit/certs/tls.crt
      tls.key_file  /opt/fluent-bit/certs/tls.key
# yamllint disable rule:line-length
  filters: |
    [FILTER] ## Filter for syslog tagging
      Name   record_modifier
      Match  EdgeNode_Syslog
      Record FileType SystemLog

    [FILTER] ## Filter for auth log tagging
      Name   record_modifier
      Match  EdgeNode_AuthLog
      Record FileType AuthLog

    [FILTER] ## Filter for Rancher agent log (kubelet log) tagging
      Name   record_modifier
      Match  EdgeNode_KubeletLog
      Record FileType KubeletLog

    [FILTER] ## Filter for logs/traces received on port
      Name   record_modifier
      Match  EdgeNode_OtelLogs
      Record FileType OpenTelemetryLogs

    [FILTER] ## Filter for adding kubernetes metadata for containers
      Name            kubernetes
      Match           Container.*
      Kube_URL        https://kubernetes.default.svc.cluster.local:443
      Kube_CA_File    /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
      Kube_Tag_Prefix Container.var.log.containers.
      Labels          off
      Annotations     off

    [FILTER] ## Rewrite the tag for logs that do not originate from an edgenode system namespace.  These logs will be considered application logs
      Name            rewrite_tag
      Match           Container.*
      Rule $kubernetes['namespace_name'] ^(?!.*(akri|calico-system|cattle-fleet-system|cattle-impersonation-system|cattle-system|cattle-ui-plugin-system|cdi|cert-manager|default|east|edge-system|gatekeeper-system|ingress-nginx|intel-gpu-extension|interconnect|istio-operator|istio-system|kube-node-lease|kube-public|kube-system|kubevirt|local|metallb-system|nfd|observability|openebs|orchestrator-system|sriov-network-operator|tigera-operator|west)).*$ Application_EdgeNode.var.log.containers.$TAG[4].log false

    [FILTER] ## Filter for adding host name of Edge Node to all logs
      Name   record_modifier
      Match  *
      Record Hostname global.fleet.clusterLabels.edge-orchestrator.intel.com/clustername

    [FILTER] ## Filter for adding UUID of Edge Node to all logs
      Name   record_modifier
      Match  *
      Record UUID global.fleet.edge-orchestrator.intel.com/host-uuid

  outputs: |
    [OUTPUT] ## Output Edge Node Container logs.
      Name      forward
      Match     Container.*
      Unix_Path /run/platform-observability-agent/fluent-bit/container-logs.sock

    [OUTPUT] ## Output Edge Node System logs.
      Name      forward
      Match     EdgeNode_*
      Unix_Path /run/platform-observability-agent/fluent-bit/host-logs.sock

    [OUTPUT] ## Output container logs for edgenode applications. Logs not originating from an edgenode system namespace will be considered application logs
      Name      forward
      Match     Application_EdgeNode.*
      Unix_Path /run/platform-observability-agent/fluent-bit/application-logs.sock
