# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
specSchema: "DeploymentPackage"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: "intel-accelerators"
description: "Intel Accelerators K8S extension"
version: 1.4.3
forbidsMultipleDeployments: true
kind: extension

applications:
  - name: intel-device-operator
    version: 0.30.2
  - name: intel-gpu-plugin
    version: 0.30.2
  - name: intel-npu-plugin
    version: 0.35.0

defaultNamespaces:
  intel-gpu-plugin: intel-accelerator-extension
  intel-device-operator: intel-accelerator-extension
  intel-npu-plugin: intel-accelerator-extension
namespaces:
  - name: intel-accelerator-extension
    labels:
      pod-security.kubernetes.io/enforce: privileged
      name: intel-accelerator-extension

applicationDependencies:
  - name: "intel-gpu-plugin"
    requires: "intel-device-operator"
  - name: "intel-npu-plugin"
    requires: "intel-device-operator"

deploymentProfiles:
  - name: "exclusive-accelerator-alloc"
    displayName: "Exclusive accelerator allocation"
    applicationProfiles:
      - application: "intel-device-operator"
        profile: "default"
      - application: "intel-gpu-plugin"
        profile: "exclusive-gpu-alloc"
      - application: "intel-npu-plugin"
        profile: "exclusive-npu-alloc"
