# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
driver:
  env:
    - name: http_proxy
      value: "http://proxy-dmz.intel.com:912"
    - name: https_proxy
      value: "http://proxy-dmz.intel.com:912"
  upgradePolicy:
    autoUpgrade: true
    maxUnavailable: 1
toolkit:
  initContainer:
    args:
      - "--sleep-duration=30"
  env:
    - name: CONTAINERD_CONFIG
      value: /var/lib/rancher/rke2/agent/etc/containerd/config.toml.tmpl
    - name: CONTAINERD_SOCKET
      value: /run/k3s/containerd/containerd.sock
    - name: CONTAINERD_RUNTIME_CLASS
      value: nvidia
    - name: CONTAINERD_SET_AS_DEFAULT
      value: "true"
nfd:
  enabled: false
