# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
specSchema: Application
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: akri
version: 0.14.0
description: "akri base application"
kind: extension

helmRegistry: "akri-helm-registry"
chartName: "akri"
chartVersion: 0.13.8

profiles:
  - name: default
    displayName: Default
    valuesFileName: akri-values.yaml

---
specSchema: Application
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: usb-device-plugin
version: 1.2.0
description: "Exposes USB devices to the k8s cluster"
kind: extension

helmRegistry: "intel-rs-helm"
chartName: "edge-orch/en/charts/akri"
chartVersion: 1.1.1

profiles:
  - name: default
    displayName: Default
    valuesFileName: usb-device-values.yaml
    parameterTemplates:
      - name: usbList
        displayName: "USB dongle List"
        mandatory: true
        type: string
