# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
{{- range .Values.extraDeploy }}
---
{{- if typeIs "string" . }}
  {{- tpl . $ }}
{{- else }}
  {{- tpl (. | toYaml) $ }}
{{- end }}
{{- end }}