# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: sriov-network-operator-deny-from-other-namespaces
spec:
  policyTypes:
    - Ingress
  podSelector: {}
  ingress:
    - from:
        - podSelector: {}
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: allow-egress
  namespace: sriov-network-operator
spec:
  selector: name == 'sriov-network-operator' ||  app == 'network-resources-injector' || app == 'operator-webhook'
  types:
    - Egress
  egress:
    - action: Allow
      destination:
        services:
          name: kubernetes
          namespace: default
