# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
specSchema: "Application"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: trusted-workload
version: 1.0.1
description: "Deploys the necessary CRD and runtime class to enable trusted compute workloads within virtual machines."
kind: extension

helmRegistry: "intel-rs-helm"
chartName: "edge-orch/trusted-compute/charts/trusted-workload"
chartVersion: "1.4.0"

profiles:
  - name: "default"
    displayName: "Default"
    valuesFileName: "values-trusted-workload-default.yaml"
