# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
specSchema: "Application"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"


name: attestation-manager
version: 1.1.0
description: "Workload prptection and continus monitoring add-on for Kubernetes"
kind: extension

helmRegistry: "intel-rs-helm"
chartName: "edge-orch/trusted-compute/charts/attestation-manager"
chartVersion: "1.4.6"

profiles:
  - name: default
    displayName: "Default"
    valuesFileName: "values-attestation-manager-default.yaml"
---
specSchema: "Application"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: attestation-verifier
version: 1.1.0
description: "attestaion verifier of trusted compute"
kind: extension

helmRegistry: "intel-rs-helm"
chartName: "edge-orch/trusted-compute/charts/attestation-verifier"
chartVersion: "1.4.6"

profiles:
  - name: "default"
    displayName: "Default"
    valuesFileName: "values-attestation-verifier-default.yaml"

---
specSchema: "Application"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: trust-agent
version: 1.1.0
description: "Automatically restart VM when editable VM spec is updated"
kind: extension

helmRegistry: "intel-rs-helm"
chartName: "edge-orch/trusted-compute/charts/trustagent"
chartVersion: "1.4.6"

profiles:
  - name: "default"
    displayName: "Default"
    valuesFileName: "values-trust-agent-default.yaml"
---
specSchema: "Application"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: trusted-workload
version: 1.1.0
description: "Deploys the necessary CRD and runtime class to enable trusted compute workloads within virtual machines."
kind: extension

helmRegistry: "intel-rs-helm"
chartName: "edge-orch/trusted-compute/charts/trusted-workload"
chartVersion: "1.4.6"

profiles:
  - name: "default"
    displayName: "Default"
    valuesFileName: "values-trusted-workload-default.yaml"
