# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
specSchema: "DeploymentPackage"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: "trusted-compute"
description: "Trusted Compute k8s plugin for trusted workloads"
version: 0.4.1
forbidsMultipleDeployments: true
kind: extension

applications:
  - name: attestation-manager
    version: 1.0.0
  - name: attestation-verifier
    version: 1.0.0
  - name: trust-agent
    version: 1.0.0
  - name: trusted-workload
    version: 1.0.0

defaultNamespaces:
  attestation-manager: isecl
  attestation-verifier: isecl
  trust-agent: isecl
  trusted-workload: trusted-compute

deploymentProfiles:
  - name: "default-profile"
    displayName: "Default Configuration"
    applicationProfiles:
      - application: "attestation-manager"
        profile: "default"
      - application: "attestation-verifier"
        profile: "default"
      - application: "trust-agent"
        profile: "default"
      - application: "trusted-workload"
        profile: "default"
