# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
specSchema: "DeploymentPackage"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: "trusted-compute"
description: >
  Trusted Compute k8s plugin for trusted workloads.
version: 0.5.4
forbidsMultipleDeployments: true
kind: extension

applications:
  - name: attestation-manager
    version: 1.0.3
  - name: attestation-verifier
    version: 1.0.3
  - name: trust-agent
    version: 1.0.3
  - name: trusted-workload
    version: 1.0.4

defaultNamespaces:
  attestation-manager: trusted-compute
  attestation-verifier: trusted-compute
  trust-agent: trusted-compute
  trusted-workload: confidential-containers-system

namespaces:
  - name: trusted-compute
    labels:
      pod-security.kubernetes.io/enforce: privileged
      name: trusted-compute
  - name: confidential-containers-system
    labels:
      pod-security.kubernetes.io/enforce: privileged
      name: confidential-containers-system

deploymentProfiles:
  - name: "default-profile"
    displayName: "Default Configuration"
    applicationProfiles:
      - application: "attestation-manager"
        profile: "default"
      - application: "attestation-verifier"
        profile: "default"
      - application: "trust-agent"
        profile: "default"
      - application: "trusted-workload"
        profile: "default"
