# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
specSchema: "DeploymentPackage"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: "trusted-compute"
description: >
  Trusted Compute k8s plugin for trusted workloads.
version: 0.9.0
forbidsMultipleDeployments: true
kind: extension

applications:
  - name: attestation-verifier
    version: 1.4.0
  - name: trusted-workload
    version: 1.4.0
  - name: kata-deploy
    version: 1.4.0

defaultNamespaces:
  attestation-verifier: trusted-compute
  trusted-workload: kata-deploy
  kata-deploy: kata-deploy

namespaces:
  - name: trusted-compute
    labels:
      pod-security.kubernetes.io/enforce: privileged
      name: trusted-compute
  - name: kata-deploy
    labels:
      pod-security.kubernetes.io/enforce: privileged
      name: kata-deploy

deploymentProfiles:
  - name: "default-profile"
    displayName: "Default Configuration"
    applicationProfiles:
      - application: "attestation-verifier"
        profile: "default"
      - application: "trusted-workload"
        profile: "default"
      - application: "kata-deploy"
        profile: "default"
