# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
specSchema: "DeploymentPackage"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: "trusted-compute"
description: >
  Trusted Compute k8s plugin for trusted workloads. Requires cluster using a "privilege" template.
version: 0.4.4
forbidsMultipleDeployments: true
kind: extension

applications:
  - name: trusted-workload
    version: 1.0.1

defaultNamespaces:
  trusted-workload: trusted-compute

deploymentProfiles:
  - name: "default-profile"
    displayName: "Default Configuration"
    applicationProfiles:
      - application: "trusted-workload"
        profile: "default"
