# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
description: A companion Helm chart for network load-balancer for Kubernetes using standard
  routing protocols - metallb Helm chart
home: https://metallb.universe.tf
icon: https://metallb.universe.tf/images/logo/metallb-white.png
kubeVersion: '>= 1.19.0-0'
name: metallb-base
type: application
version: 0.16.0
appVersion: 0.16.0
