# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
{{ if not (eq .Values.usbList "") }}
{{ $usbs := split "," .Values.usbList }}
{{ range $i, $v := $usbs }}
{{ $parts := split ";" $v }}
---
apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: {{ $parts._0 }}
  namespace: {{ $.Release.Namespace }}
spec:
  discoveryHandler:
    name: udev
    discoveryDetails: |+
      udevRules:
      - SUBSYSTEM=="usb", ATTR{idVendor}=="{{ $parts._1 }}", ATTR{idProduct}=="{{ $parts._2 }}"
  brokerProperties: {}
  capacity: 1
{{ end }}
{{ end }}
