# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
specSchema: "Application"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: sriov-network-operator
version: 104.3.2
description: "Provisions and configures SR-IOV CNI plugin and Device plugin"
kind: extension

helmRegistry: "intel-rs-helm"
chartName: "edge-orch/en/charts/sriov"
chartVersion: "104.3.2"

profiles:
  - name: default
    displayName: "Default"
    valuesFileName: "values-default.yaml"
