# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
specSchema: "DeploymentPackage"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: "sriov"
description: "Provisions and configures SR-IOV CNI plugin and Device plugin"
version: 0.3.5
forbidsMultipleDeployments: true
kind: extension

applications:
  - name: sriov-network-operator
    version: 1.5.0

defaultNamespaces:
  sriov-network-operator: sriov-network-operator

deploymentProfiles:
  - name: "default-profile"
    displayName: "Default Configuration"
    applicationProfiles:
      - application: "sriov-network-operator"
        profile: "default"
