---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
name: Pre-Merge CI Pipeline

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-checks:
    runs-on: ${{ github.repository_owner == 'intel' && 'intel-ubuntu-latest' || 'ubuntu-latest' }}
    outputs:
      filtered_projects: ${{ steps.filter-changes.outputs.filtered_projects }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          persist-credentials: false
      - name: "Verify Branch Name"
        uses: open-edge-platform/orch-ci/verify-branch-name@76700c2fb6d547733b9218d9638dca43f5296399 # v0.1.52
      - name: "Discover Changed Subfolders"
        id: discover-changes
        uses: open-edge-platform/orch-ci/discover-changed-subfolders@76700c2fb6d547733b9218d9638dca43f5296399 # v0.1.52
      - name: "Filter Out Unwanted Changed Subfolders"
        id: filter-changes
        run: |
          folders_to_remove='[".github",".reuse","LICENSES"]'

          changed_projects='${{ steps.discover-changes.outputs.changed_projects }}'
          filtered_projects=$(echo "$changed_projects" | jq -cr --argjson folders_to_remove "$folders_to_remove" 'map(select(. as $item | $folders_to_remove | index($item) | not))')
          echo "filtered_projects=$filtered_projects" >> $GITHUB_OUTPUT
  pre-merge-pipeline:
    needs: pre-checks
    if: ${{ needs.pre-checks.outputs.filtered_projects != '[]' }}
    strategy:
      fail-fast: false
    uses: open-edge-platform/orch-ci/.github/workflows/pre-merge.yml@76700c2fb6d547733b9218d9638dca43f5296399 # v0.1.52
    with:
      run_security_scans: true
      run_version_check: true
      run_dep_version_check: false
      run_build: false
      run_lint: true
      run_test: false
      run_validate_clean_folder: false
      run_docker_build: true
      run_helm_build: true
      run_artifact: false
      project_folder: ${{ matrix.project_folder }}
    secrets:
      inherit # zizmor: ignore[secrets-inherit]
  final-check:
      runs-on: ubuntu-latest
      if: ${{ always() }}
      needs: [pre-merge-pipeline]
      steps:
        - name: Final Status Check
          run: |
            pre_merge_pipeline_result="${{ needs.pre-merge-pipeline.result }}"
            echo "Pre-merge pipeline result: $pre_merge_pipeline_result"

            if [ "$pre_merge_pipeline_result" == "success" ] || [ "$pre_merge_pipeline_result" == "skipped" ]; then
              echo "Pre-merge check passed successfully."
            else
              echo "Pre-merge checks failed. PR can't get merged"
              exit 1
            fi
